@url = http://127.0.0.1:8080/generos
GET {{url}}

###
GET {{url}}/1

###
POST {{url}}
Content-Type: application/json

{
    "nome" : "Fantasia"
}

###
PUT {{url}}/3
Content-Type: application/json

{
    "nome" : "Terror (Modificado)"
}

###
DELETE {{url}}/3