@url = http://127.0.0.1:8080/livros

GET {{url}}
###
POST {{url}}
Content-Type: application/json

{
    "titulo" : "Teste",
    "id_genero" : 1,
    "autores": [1, 2]
}

# {
#     "titulo": "Assassinato no Expresso do Oriente",
#     "id_genero": 2
# }

###
PUT {{url}}/2
Content-Type: application/json

{
    "titulo" : "A Sociedade do Anel",
    "id_genero": 1
}